### ISSUE TITLE
Code Examples

### ISSUE THREAD

**Issue by Wallman** [openrewrite/rewrite-kotlin#104]
I'm not sure about the state of this repository, if it has enough implementation to do some small recipes.
If possible I would love some code examples to get going!

Thanks for all the great work!

**Comment by timtebeek** [comment]
Hi @Wallman ! We're working towards parity with our other JVM languages, reusing the same building blocks where we can. This is already used in https://github.com/arrow-kt/rewrite-arrow, where it aims to smoothen the upgrade to Arrow 1.2.x & 2.x. That also contains the most up to date samples on [using declarative yaml recipes](https://github.com/arrow-kt/rewrite-arrow/tree/main/src/main/resources/META-INF/rewrite) and implementing [imperative migration recipes](https://github.com/arrow-kt/rewrite-arrow/tree/main/src/main/java/arrow).

If you have any other questions or suggestions you're welcome to ask them here, or in [our Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA) `#questions` channel.

**Comment by Wallman** [comment]
Lovely, thanks! Maybe this could be added to the README? Or just left here :)

**Comment by timtebeek** [comment]
We expect to merge this repository into openrewrite/rewrite, similar to what we've done with rewrite-groovy in the past. We can keep this issue open to document the code examples until then, as any addition to the README is likely lost upon a merge into rewrite.

**Comment by timtebeek** [comment]
We've since come a bit further with building out the kotlin language and recipe support, and adding code examples. You can find them by [searching for `@DocumentExample` in this repository](https://github.com/search?q=repo%3Aopenrewrite%2Frewrite-kotlin%20Documentexample&type=code). That annotation also ensures the recipes are documented with those code samples over on https://docs.openrewrite.org/recipes/kotlin

Hope that sufficiently solves this issue for you! If not please let me know and we'll reopen and explore further.
