### ISSUE TITLE
Parsing failure on trailing lambda expression

### ISSUE THREAD

**Issue by nomisRev** [openrewrite/rewrite-kotlin#22]
Parsing failure on `FirLambdaArgumentExpression`.
Cause: building the function call arguments assumes the arguments are comma delimited.
Kotlin allows trailing lambda to be a part of the method invocation per [docs](https://kotlinlang.org/docs/lambdas.html#passing-trailing-lambdas).
```kotlin
                interface Test < in R > {
                    public fun < B > shift ( r : R ) : B
                    public fun ensure( condition : Boolean , shift : ( ) -> R ) : Unit =
                        if ( condition ) Unit else shift( shift ( ) )
                }
```

```kotlin
                fun Test < String > . test ( ) : Int {
                    ensure ( false ) { "failure" } // This is a method invocation with 2 arguments
                    return 1
                }
```

Reproducible example: https://github.com/nomisRev/rewrite-arrow/pull/3

The assertion message is incorrect, see below. Inspecting the code it seems that `after` in [`Assertions.kotlin` on line 49](https://github.com/openrewrite/rewrite-kotlin/blob/045630d3e129443ca41b9eca1757b5684dc088fb/src/main/java/org/openrewrite/kotlin/Assertions.java#L49) is never used, and discarded. 

```text
org.opentest4j.AssertionFailedError: [When parsing and printing the source code back to text without modifications, the printed source didn't match the original source code. This means there is a bug in the parser implementation itself. Please open an issue to report this, providing a sample of the code that generated this error!] 
expected: 
  "package com.yourorg
  
  import arrow.core.continuations.EffectScope
  
  fun EffectScope<String>.test(): Int {
    ensure(false) { "failure" }
    return 1
  }"
 but was: 
  "package com.yourorg
  
  import arrow.core.continuations.EffectScope
  
  fun EffectScope<String>.test(): Int {
    ensure(false,) { "failure")
    return 1
  }"
```

but actually expected:

```text
org.opentest4j.AssertionFailedError: [When parsing and printing the source code back to text without modifications, the printed source didn't match the original source code. This means there is a bug in the parser implementation itself. Please open an issue to report this, providing a sample of the code that generated this error!] 
expected: 
  "package com.yourorg
  
  import arrow.core.continuations.EffectScope
  
  fun EffectScope<String>.test(): Int {
    ensure(false) { "failure" }
    return 1
  }"
 but was: 
  "package com.yourorg
   
   import arrow.core.raise.Raise
   import arrow.core.raise.ensure
   
   fun Raise<String>.test(): Int {
     ensure(false) { "failure" }
     return 1
   }"
```

**Comment by traceyyoshima** [comment]
Hi @nomisRev, thanks for reporting the issue!
To provide some context to the message and what is happening:

The message, `"When parsing and printing the source code back to text without modifications, the printed source didn't match the original source code. This means there is a bug in the parser implementation itself. Please open an issue to report this, providing a sample of the code that generated this error!"` is meant to communicate that there was an issue parsing the Kotlin code, and we need to fix something in the `KotlinParser.`

I.E.:
`ensure(false) { "failure" }` vs. `ensure(false,) { "failure")`

The reason why the J.MethodInvocation is not visited in https://github.com/openrewrite/rewrite-kotlin/issues/21 is due to the initial check on parsing. The recipe isn't run because the `Kotlin` code was found to be incorrectly parsed.

Thanks again for reporting the issue! :)
