### ISSUE TITLE
Parsing error: missing annotation

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-kotlin#408]
There are two issues in the test:

1. Idempotent print issue on the second parameter.
2. Annotations are removed from the parameterized types.

```java
    @ParameterizedTest
    @ValueSource(strings = {
      "String",
      "Map<*, *>"
    })
    void test(String input) {
        rewriteRun(
          kotlin(ANNOTATION),
          kotlin(
            """
              class Test(
                val map: Map<@Ann %s, @Ann %s> = emptyMap()
              )
              """.formatted(input, input)
          )
        );
    }
```

**Comment by kunli2** [comment]
The 1st case is fixed by https://github.com/openrewrite/rewrite-kotlin/commit/f9e3284117f243c531860d0295fe55a57f5c6111

However, the 2nd case is different, compared to `String ` which is parsed to a `J.Identifier`, so it can have leading annotations, however,  `Map<*, *>` is parsed to a `J.ParameterizedType` which has not a space for leading annotations, we probably want to add a leading annotation field to  `J.ParameterizedType` to support this. 

+ @traceyyoshima , @knutwannheden for ideas.

**Comment by traceyyoshima** [comment]
@kunli2 `J.ParameterizedType` contains a `JContainer<Expression>` for the type parameters, so you may add it with `AnnotatedExpression`.

Background: Knut added `AnnotatedExpression`, since expressions may contain annotations in Kotlin. So, any valid position of an expression might contain annotations, too.

**Comment by kunli2** [comment]
Talked with @knutwannheden , we should use `J.AnnotatedType` here but not `K.AnnotatedExpression`, going to revise this  change.

**Comment by knutwannheden** [comment]
@traceyyoshima Yes, I think `J.AnnotatedType` makes sense here, as this is also how we use it in Java when parsing something like `List<@Nullable String>`.
