### ISSUE TITLE
AddImport not working for Kotlin

### ISSUE THREAD

**Issue by nomisRev** [openrewrite/rewrite-kotlin#45]
Not sure if this was already reported elsewhere in OpenRewrite. Reproducible test, and use-case can be found in https://github.com/openrewrite/rewrite-kotlin/pull/44

**Comment by traceyyoshima** [comment]
Hi @nomisRev :), I added a review to the PR and provided information on why AddImport isn't executing.
It isn't that the recipe isn't working on Kotlin, but it's not called due to the condition of the old type.

**Comment by nomisRev** [comment]
Hey @traceyyoshima, thank you so much for looking into this!

I applied your changes, and learned some new things like using `MethodMatcher` instead of my custom predicate and `getSingleSourceApplicableTest` 🙌 

I am still unsure which is the correct way to specify the `import`, should I specify the Java equivalent to `AddImport` or the Kotlin import.

```java
maybeAddImport("arrow.core.raise.RaiseKt", "ensure");
maybeAddImport("arrow.core.raise.ensure");
```

After applying your suggestions it is however still not working. The test case is still failing, is this perhaps due to the also failing test case in https://github.com/openrewrite/rewrite-kotlin/pull/44/files?

**Comment by traceyyoshima** [comment]
Hi @nomisRev, my apologies, I probably didn't explain the changes very well in your PR.

I'll provide more context here:
Ideally, `AddImport` is only called when necessary after `ChangeType`, since `ChangeType` will add/remove imports and update static imports automatically.

I pushed changes that will work for now. Using `maybeAddImport("arrow.core.raise.Raise", "ensure");`, will add the import, BUT it will produce the wrong output since as you mentioned previously, `static` does not exist in `kotlin`.

I think we can close this issue, but open a new one that states "KotlinPrinter outputs invalid import"`. What do you think?

**Comment by nomisRev** [comment]
Yes, we can close this issue 👍

> Using maybeAddImport("arrow.core.raise.Raise", "ensure");, will add the import, BUT it will produce the wrong output since as you mentioned previously, static does not exist in kotlin.
> I think we can close this issue, but open a new one that states "KotlinPrinter outputs invalid import"`. What do you think?

Do you mean `maybeAddImport("arrow.core.raise.Raise", "ensure")`, or `maybeAddImport("arrow.core.raise.RaiseKt", "ensure")`? If the former, perfect. If the latter, that is an implementation detail of Kotlin/JVM.. and might seem foreign for someone trying to leverage rewrite-kotlin for JS or Natie `sourceSets`.

**Comment by traceyyoshima** [comment]
@nomisRev It's based on the NEW_FQN of `ChangeType`. The former works as `maybeAddImport("arrow.core.raise.Raise", "ensure");` works, because the type is changed to `arrow.core.raise.Raise#ensure`.

If `ChangeType` changed the type to `arrow.core.raise.RaiseKt`, then it would be a different story, but that is up to the recipe author. :)

I will say that in certain cases, types from the KotlinCompiler did show up as `{Type}Kt`. So, I may need to adjust the code to remove the `Kt` for a smoother user experience.
