### ISSUE TITLE
Mass ingest Kotlin projects

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-kotlin#472]
Steps:

1. [Link](https://github.com/search?q=kotlin+language%3AKotlin&type=repositories&l=Kotlin&s=stars&o=desc) to most starred Kotlin projects.
2. Check if the project will be successfully ingested:
     - `Maven` projects should work.
     - `Gradle` projects require the `jvm` or the `kotlin multiplatform` plugin. 
         - Note: The android plugin is not supported and will result in PlainText sources, so we do not want to add Android projects that only contain the Android plugin as ingest jobs.
6. Add ingest jobs to Jenkins via https://github.com/moderneinc/jenkins-ingest.
     - Follow the steps in the readme.
8. Add the new repos to the SAAS organizations.

**Comment by kunli2** [comment]
@traceyyoshima, I have added the automated script and auto generated more kotlin repos to the ingestion by https://github.com/moderneinc/jenkins-ingest/pull/184, 
The rest part is to filter and add more to the SAAS organization,  I assigned this to you since you are more familiar and will be more efficient.

**Comment by traceyyoshima** [comment]
Closing issue as completed: @kunli2 has added the repositories with Kotlin CUs to the SAAS.
